[tool.poetry]
name = "repl_python_google-chrome"
version = "0.1.0"
description = " "
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
webbot = "^0.34"

[tool.poetry.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-blackend = "poetry.core.masonry.api"
